project:
  type: book

book:
  title: "CM_4450_B21__Quarto_Book"
  author: "Priyanga D. Talagala"
  date: "3/2/2026"
  chapters:
    - index.qmd
    - 1_Bayesian_Thinking_in_AI.qmd
    - 2_Bayesian_computation.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{scrlayer-scrpage}
        \clearpairofpagestyles
        \ofoot{\thepage}
        \lofoot{Prepared by Dr. Priyanga D. Talagala  (Copyright 2026 P. D. Talagala)}

editor: visual

